name: CD

on:
  push:
    branches: [ main, beta ]
  workflow_dispatch:


jobs:
  build_and_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm ci
      working-directory: host-example

    - name: Build
      run: npm run build
      working-directory: host-example

    # Locally we debug the build output
    - name: List dist (local only)
      if: ${{ env.ACT }}
      run: ls -alR host-example/dist

    - name: Parse git commit
      run: echo GH_REL_TAG=$(git rev-parse --short HEAD 2> /dev/null | sed "s/\(.*\)/v0-\1/") >> $GITHUB_ENV

    # Locally we debug the tag parse
    - run: echo ${{ env.GH_REL_TAG }}
      if: ${{ env.ACT }}

    # Remotely we create and push the tag
    - name: Create Release Tag
      run: git tag ${{ env.GH_REL_TAG }} && git push origin ${{ env.GH_REL_TAG }}
      if: ${{ !env.ACT }}

    - name: Package bin
      run: |
        mkdir rel
        zip rel/host-example-${{ env.GH_REL_TAG }}.zip -r host-example &&
        echo "Packaged."

    # Remotely we create the release from the tag
    - name: GH Release
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: ${{ env.GH_REL_TAG }}
        prerelease: ${{ github.ref != 'refs/heads/main' }}
        generate_release_notes: true
        files: rel/*.zip
