name: Host Example CI

on:
  pull_request:
    branches: [ main, beta ]
    paths:
      - "host-example/**/*"
      - ".github/workflows/host-example.ci.yml"
jobs:
  host_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install dependencies
      run: npm ci
      working-directory: host-example
    - name: Build
      run: npm run build
      working-directory: host-example
